# Generated by Django 5.0.3 on 2024-06-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre_app', '0003_bloque_latitud_bloque_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloque',
            name='entrada_campus',
            field=models.BooleanField(default=False),
        ),
    ]
